[package]
name = "zero-primitives"
version = "1.0.0"
authors = ["zero collective <play@zero.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.103", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

sp-application-crypto = { version = "3.0.0", default-features = false, path = "../../primitives/application-crypto" }
sp-core = { version = "3.0.0", default-features = false, path = "../../primitives/core" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../primitives/runtime"}
sp-std = { version = "3.0.0", default-features = false, path = "../../primitives/std"}
sp-io = { version = "3.0.0", default-features = false, path = "../../primitives/io"}

frame-system = { version = "3.0.0", default-features = false, path = "../../frame/system" }

[dev-dependencies]
frame-support = { version = "3.0.0", path = "../../frame/support"}
frame-system = { version = "3.0.0", path = "../../frame/system"}

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"frame-system/std",
]
